swagger: '2.0'

schemes: 
  - http
  - https
  
host: localhost:8085
basePath: /bytebank-api/v1

info:
  version: 1.0.0
  title: ByteBank API
  description: Administra a movimentação bancária do correntista e controla o acesso através de CPF e senha
  termsOfService: http://localhost:8085/bytebank-api/v1/termo
  contact:
    name: Suporte
    url:  http://localhost:8085/bytebank-api/v1/support
    email: suporte@bytebank.com.br

consumes:
  - application/json
produces:
  - application/json

tags:
  - name: cliente
  - name: conta
  - name: transacao
  - name: extrato

paths:
  '/cliente':
    post:
      tags:
        - cliente
      summary: Cadastra cliente
      description: Cadastra um novo cliente
      operationId: cadastraCliente
      security:
        - BasicAuth: []
      parameters:
        - in: body
          name: cliente_
          schema:
            $ref: '#/definitions/Cliente'
      responses:
        201:
          description: Cliente criado com sucesso
          schema:
            $ref: '#/definitions/Cliente'
        400:
          description: Requisição inválida
        401:
          description: Requisição não autorizada
        500:
          description: Erro interno no servidor

  '/conta/{agencia}/{numero}/{digito}/saldo':
    get:
      tags: 
        - conta 
      summary: Consulta o saldo
      description: O saldo na conta do cliente
      operationId: consultaSaldo
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: agencia
          type: integer
          format: int32
          required: true
        - in: path
          name: numero
          type: integer
          format: int64
          required: true
        - in: path
          name: digito
          type: integer
          format: int32
          required: true
        - in: header
          name: Authorization
          type: string
          required: true
      responses:
        200:
          description: Consulta realizada com sucesso
          schema:
            type: number
            format: double
        401:  
          description: Requisição não autorizada
        400:
          description: Requisição inválida
        500:
          description: erro no servidor
    
  '/transacao':
    post:
      tags: 
        - transacao
      summary: Cadastra uma transação
      description: Cadastra uma nova transação de débito ou crédito
      operationId: cadastraTransacao
      security: 
        - BasicAuth: []
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - in: body
          name: transacao
          schema:
            $ref: '#/definitions/Transacao'
          required: true
        - in: query
          name: tipo
          type: string
          enum:
            - debito
            - credito
          required: true
      responses:
        201:
          description: Transação cadastrada com sucesso
          schema:
            $ref: '#/definitions/Transacao'
    put:
      tags: 
        - transacao
      summary: Altera uma transação
      description: Altera uma transação de acordo com o ID fornecido
      operationId: atualizaTransacao
      security:
        - BasicAuth: []
      parameters:
        - in: query
          name: codigo
          type: integer
          format: int32
          required: true
        - in: header
          name: Authorization
          type: string
          required: true
        - in: query
          name: valor
          type: number
          format: double
          required: true
      responses:
        204:
          description: Transação alterada com sucesso
        401:  
          description: Requisição não autorizada
        400:
          description: Requisição inválida
        500:
          description: erro no servidor
    delete:
      tags: 
        - transacao
      summary: Remove uma transação
      description: Remove a transação especificada
      operationId: excluiTransacao
      security:
        - BasicAuth: []
      parameters:
        - in: query
          name: codigo
          type: integer
          format: int32
          required: true
        - in: header
          name: Authorization
          type: string
          required: true
      responses:
        204:
          description: Transação alterada com sucesso
        401:  
          description: Requisição não autorizada
        400:
          description: Requisição inválida
        500:
          description: erro no servidor

  '/extrato/{agencia}/{numero}/{digito}':
    get:
      tags: 
        - extrato
      summary: Obtém o extrato
      description: Obtém o extrato do cliente
      security:
        - BasicAuth: []
      operationId: consultaExtrato
      parameters:
        - in: path
          name: agencia
          type: integer
          format: int32
          required: true
        - in: path
          name: numero
          type: integer
          format: int64
          required: true
        - in: path
          name: digito
          type: integer
          format: int32
          required: true
        - in: header
          name: Authorization
          type: string
          required: true
      responses:
        200:
          description: Consulta realizada com sucesso
          schema:
            $ref: '#/definitions/Extrato'
        401:  
          description: Requisição não autorizada
        400:
          description: Requisição inválida
        500:
          description: erro no servidor

definitions:
  Cliente:
    type: object
    properties:
      id: 
        type: integer
        format: int64
        example: 123456
      titular:
        type: string
        example: Ana Silva
      cpf:
        type: string
        minLength: 11
        maxLength: 11
        example: 09876543211
      senha:
        type: string
        format: password
        example: senha123
      conta: 
        type: array
        items:
          $ref: '#/definitions/Conta'
  Conta:
    type: object
    properties:
      agencia:
        type: integer
        format: int32
        example: 975
      numero:
        type: integer
        format: int64
        example: 1234567
      digito:
        type: integer
        format: int32
        example: 7
      saldo:
        type: number
        format: double
        example: 101.34
      cliente:
        $ref: '#/definitions/Cliente' 
      transacoes:
        type: array
        items:
          $ref: '#/definitions/Transacao'
  Transacao:
    type: object  
    properties:
      id:
        type: integer
        format: int64
      tipo:
        type: string
        enum:
          - credito
          - debito
      valor:
        type: number
        format: double
      data:
        type: string
        format: date-time
      conta:
        $ref: '#/definitions/Conta' 
  Extrato:
    type: object
    properties:
      transacoes:
        type: array
        items:
          $ref: '#/definitions/Transacao'
securityDefinitions:
  BasicAuth: 
    type: basic
